permalink: /:title/
markdown: kramdown

collections:
 projects:
  output: true 
  permalink: /projects/:path/
 pages:
  output: true
  permalink: /pages/:path/
 blogposts:
  output: true
  permalink: /blogposts/:path/



kramdown:  
  parse_block_html: true